Repository code-computerlove/nextjs-starter, pull requests merged in 2022-11, with the labels that each got.

#13 feat: added husky and lint-staged
  .husky/pre-commit
  RUNBOOK.md
  lint-staged.config.js
  package-lock.json
  package.json
Labels: enhancement

#12 feat: Storybook integration
  .npmrc
  .storybook/main.js
  .storybook/preview.js
  RUNBOOK.md
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  postcss.config.js
  public/mockServiceWorker.js
  src/api/mocks/browser.ts
  src/api/mocks/handlers.ts
  src/api/mocks/server.ts
  src/api/testMockFetch.ts
  src/components/atoms/button/index.module.css
  src/components/atoms/button/index.stories.tsx
  src/components/atoms/button/index.tsx
  src/components/atoms/meta/index.tsx
  src/components/layout/header/index.module.css
  src/components/layout/header/index.tsx
  src/components/organisms/example-counter/index.module.css
  src/components/organisms/example-counter/index.tsx
  src/components/organisms/example-fetch/index.module.css
  src/components/organisms/example-fetch/index.stories.tsx
  src/components/organisms/example-fetch/index.tsx
  src/pages/_app.tsx
  src/pages/api/hello.ts
  src/pages/home/index.module.css
  src/pages/home/index.tsx
  src/pages/index.tsx
  src/pages/mock-api.tsx
  src/pages/test/index.module.css
  src/pages/test/index.tsx
  src/styles/globals.css
  styles/Home.module.css
  styles/globals.css
  tsconfig.json
Labels: enhancement

#14 feat: add .editorconfig
  .editorconfig
  RUNBOOK.md
Labels: enhancement

#16 feat: postcss runbook instructions and postcss dep updates
  RUNBOOK.md
  package-lock.json
  package.json
  src/pages/_app.tsx
Labels: enhancement

#15 Feat/adding jest tests
  .eslintrc.js
  jest.config.js
  package-lock.json
  package.json
  postcss.config.js
  src/api/hello.ts
  src/components/atoms/button/index.module.css
  src/components/atoms/button/index.test.tsx
  src/components/atoms/button/linkButton.test.tsx
  src/pages/api/hello.api.ts
  src/pages/index.tsx
  src/styles/Home.module.css
  src/vitest-env.d.ts
  test/jest-setup.ts
  test/mocks/file-mock.js
  test/mocks/style-mock.js
  tsconfig.json
  vitest.config.js
Labels: enhancement

#19 feat: add dependency reviews
  .github/workflows/dependency-review.yml
Labels: dependencies

#18 feat: added dependabot config
  .github/dependabot.yml
Labels: enhancement

#20 feat: add conventional commit validation to PR titles
  .github/workflows/semantic-title.yml
Labels: enhancement

#25 feat: added automated a11y checks in devtools and a11y test helper
  package-lock.json
  package.json
  src/components/atoms/button/index.test.tsx
  src/components/atoms/button/linkButton.test.tsx
  src/pages/_app.tsx
  src/utils/reportAccessibility.ts
  test/jest-setup.ts
  test/test-utils.ts
Labels: enhancement

#24 chore: test cleanup and run sheet
  RUNBOOK.md
  jest.config.js
  package-lock.json
  package.json
  src/vitest-env.d.ts
  test/test-setup.ts
  test/test-utils.ts
  vitest.config.js
Labels: bug, enhancement

#26 docs: updated the Runbook for adding a11y tests and changed helper name
  RUNBOOK.md
  src/components/atoms/button/index.test.tsx
  src/components/atoms/button/linkButton.test.tsx
  test/test-utils.ts
Labels: documentation

#31 feat: hygen component templates
  RUNBOOK.md
  generators/new/component/component.ejs.t
  generators/new/component/prompt.js
  generators/new/component/story.ejs.t
  generators/new/component/style.ejs.t
  generators/new/component/unit.ejs.t
  package-lock.json
  package.json
Labels: enhancement

#32 feat: added commitlint checks to Husky for commit messages
  .husky/commit-msg
  RUNBOOK.md
  commitlint.config.js
  package-lock.json
  package.json
Labels: enhancement

#33 fix: removing a webpack comment that was causing an error on the FE
  src/utils/reportAccessibility.ts
Labels: bug

#34 fix: adds prettier and linting for CSS and SCSS files
  lint-staged.config.js
Labels: bug

#41 fix: fixed the linters not working by install old postcss parser
  .storybook/main.js
  package-lock.json
  package.json
  src/api/hello.ts
  src/pages/mock-api.tsx
  src/pages/test/index.tsx
  src/styles/Home.module.css
  src/styles/globals.css
Labels: bug

#43 feat: changing test file name
  generators/new/component/unit.ejs.t
Labels: enhancement
